#ifndef APP_CONFIG_H
#define APP_CONFIG_H
#define FAN_PWM_FREQUENCY_HZ 25000UL
#define FAN_TACH_PULSES_PER_REV 2UL
#define TACH_MEASUREMENT_WINDOW_MS 1000UL
#define POWER_ON_DUTY_PERCENT 0U
#define BOOT_CONNECTION_TIMEOUT_MS 300000UL
#define HOST_COMM_TIMEOUT_MS 30000UL
#define FAILSAFE_DUTY_DEFAULT 50U
#define FAILSAFE_DUTY_MIN 20U
#define FAILSAFE_DUTY_MAX 100U
#define MIN_DUTY_PERCENT 0U
#define MAX_DUTY_PERCENT 100U
#define FEATURE_POWER_FAULT 0
#ifndef FEATURE_DEBUG_TEST
#define FEATURE_DEBUG_TEST 0
#endif
#ifndef FEATURE_DFU_TEST
#define FEATURE_DFU_TEST 0
#endif
#ifndef FEATURE_USB_DEVICE
#define FEATURE_USB_DEVICE 1
#endif
#ifndef FEATURE_USB_DIAG
#define FEATURE_USB_DIAG 0
#endif
#ifndef FEATURE_USB_ENUM_TRACE
#define FEATURE_USB_ENUM_TRACE 0
#endif
#ifndef FEATURE_USB_ATTACH_DIAG
#define FEATURE_USB_ATTACH_DIAG 0
#endif
#ifndef FEATURE_USB_SETUP_DIAG
#define FEATURE_USB_SETUP_DIAG 0
#endif
#ifndef FEATURE_USB_DEVICE_DESC_DIAG
#define FEATURE_USB_DEVICE_DESC_DIAG 0
#endif
#ifndef FEATURE_USB_SET_ADDRESS_DIAG
#define FEATURE_USB_SET_ADDRESS_DIAG 0
#endif
#ifndef FEATURE_USB_CONFIG_DIAG
#define FEATURE_USB_CONFIG_DIAG 0
#endif
#ifndef FEATURE_USB_POST_ADDRESS_DIAG
#define FEATURE_USB_POST_ADDRESS_DIAG 0
#endif
#ifndef FEATURE_USB_POST_ADDRESS_FIX_DIAG
#define FEATURE_USB_POST_ADDRESS_FIX_DIAG 0
#endif
#ifndef FEATURE_USB_CONFIG_LENGTH_DIAG
#define FEATURE_USB_CONFIG_LENGTH_DIAG 0
#endif
#ifndef FEATURE_USB_CONFIG_IN_DIAG
#define FEATURE_USB_CONFIG_IN_DIAG 0
#endif
#ifndef FEATURE_USB_CONFIG_RUNTIME_DIAG
#define FEATURE_USB_CONFIG_RUNTIME_DIAG 0
#endif
#ifndef FEATURE_USB_BINARY_WLENGTH9_DIAG
#define FEATURE_USB_BINARY_WLENGTH9_DIAG 0
#endif
#ifndef FEATURE_USB_BINARY_CONFIG_SEEN_DIAG
#define FEATURE_USB_BINARY_CONFIG_SEEN_DIAG 0
#endif
#ifndef FEATURE_USB_BINARY_POST_ADDRESS_SETUP_DIAG
#define FEATURE_USB_BINARY_POST_ADDRESS_SETUP_DIAG 0
#endif
#ifndef FEATURE_USB_BINARY_POST_ADDRESS_GET_DESCRIPTOR_DIAG
#define FEATURE_USB_BINARY_POST_ADDRESS_GET_DESCRIPTOR_DIAG 0
#endif
#ifndef FEATURE_USB_BINARY_POST_ADDRESS_CONFIG_TYPE_DIAG
#define FEATURE_USB_BINARY_POST_ADDRESS_CONFIG_TYPE_DIAG 0
#endif
#ifndef FEATURE_USB_BINARY_POST_ADDRESS_STRING_TYPE_DIAG
#define FEATURE_USB_BINARY_POST_ADDRESS_STRING_TYPE_DIAG 0
#endif
#ifndef FEATURE_USB_RAM_TRACE_DIAG
#define FEATURE_USB_RAM_TRACE_DIAG 0
#endif
#ifndef FEATURE_USB_EP0_CORRELATION_TRACE_V3
#define FEATURE_USB_EP0_CORRELATION_TRACE_V3 0
#endif
#ifndef FEATURE_USB_DELAYED_ATTACH_MS
#define FEATURE_USB_DELAYED_ATTACH_MS 0UL
#endif
#ifndef USB_DIAG_TIMEOUT_MS
#define USB_DIAG_TIMEOUT_MS 30000UL
#endif
#define USB_REPORT_SIZE 64U
#endif
